### ISSUE TITLE
fat-aar依赖问题

### ISSUE THREAD

**Issue by baoJiePro** [moonljt521/flutter_module_package#2]
flutter项目集成了image_picker的plugin，合并aar出现
Attribute provider#io.flutter.plugins.imagepicker.ImagePickerFileProvider@authorities value=(com.example.qdingflutter.flutter.image_provider) from [:flutter] AndroidManifest.xml:25:13-82
        is also present at [:image_picker] AndroidManifest.xml:14:13-74 value=(com.example.qdingflutter.host.flutter.image_provider).
        Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:23:9-31:20 to override.
的问题

**Comment by moonljt521** [comment]
你在主项目里配置下AndroidManifest，用replace合并覆盖的标签，比如这样，tools:replace="android:icon,android:name"

**Comment by moonljt521** [comment]
<application
        tools:replace="android:icon,android:name"
        android:label="@string/app_name"
        android:theme="@style/Theme.Main">
